#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
 autocomplete_method = "coc"
 bootstrap_after = 'myspacevim#after'
 bootstrap_before = 'myspacevim#before'
 buffer_index_type = 4
 # set spacevim theme. by default colorscheme layer is not loaded,
 # if you want to use more colorscheme, please load the colorscheme
 # layer
 colorscheme = "gruvbox"
 colorscheme_bg = "dark"
 # Disable guicolors in basic mode, many terminal do not support 24bit
 # true colors
 enable_guicolors = true
 enable_statusline_mode = false
 enable_tabline_filetype_icon = true
 # Disable statusline separator, if you want to use other value, please
 # install nerd fonts
 statusline_iseparator = "arrow"
 statusline_separator = "arrow"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
    name = "fzf"

[[layers]]
  name = "lsp"
  filetypes = [
    "html",
    "javascript",
    "typescript"
  ]

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#go" 
